variables:
  SCAN_PATH: $SCAN_PATH
  SCAN_ARGS: $SCAN_ARGS

stages:
  - test
  - scan

owasp_depcheck_scan:
  stage: scan
fortify_scanning:
  stage: test
  rules:
    - if: $SKIP_FORTIFY != 'true'
include:
- project: 'DSO-Millennium-Falcon/gitlab-ci-templates/scanning-templates'
  ref: master
  file: '/owasp-depcheck.gitlab-ci.yml'  
- project: 'DSO-Millennium-Falcon/gitlab-ci-templates/scanning-templates'
  ref: master
  file: '/fortify-scanning.yml'