const REQUEST_RENDER = 'render'
const REQUEST_ATTACH_MEDIA = 'attach_media'
const REQUEST_PROCESS_SOURCE = 'process_source'
const REQUEST_GEOTIFF_RASTER = 'geotiff_raster'

export {
  REQUEST_RENDER,
  REQUEST_ATTACH_MEDIA,
  REQUEST_PROCESS_SOURCE,
  REQUEST_GEOTIFF_RASTER
}
