const WEB_MERCATOR = 'EPSG:3857'
const WORLD_GEODETIC_SYSTEM = 'EPSG:4326'
const WORLD_GEODETIC_SYSTEM_CRS = 'CRS:84'

const WEB_MERCATOR_CODE = 3857
const WORLD_GEODETIC_SYSTEM_CODE = 4326
const WORLD_GEODETIC_SYSTEM_CRS_CODE = 84

const WEB_MERCATOR_DISPLAY_TEXT = 'EPSG:3857 (Web Mercator)'
const WORLD_GEODETIC_SYSTEM_DISPLAY_TEXT = 'EPSG:4326 (World Geodetic System 1984)'

const EPSG = 'EPSG'
const COLON_DELIMITER = ':'

export {
  WEB_MERCATOR,
  WORLD_GEODETIC_SYSTEM,
  WORLD_GEODETIC_SYSTEM_CRS,
  WEB_MERCATOR_CODE,
  WORLD_GEODETIC_SYSTEM_CODE,
  WORLD_GEODETIC_SYSTEM_CRS_CODE,
  WEB_MERCATOR_DISPLAY_TEXT,
  WORLD_GEODETIC_SYSTEM_DISPLAY_TEXT,
  EPSG,
  COLON_DELIMITER
}
