import {
  mdiPineTree,
  mdiBank,
  mdiSilverwareForkKnife,
  mdiHamburger,
  mdiCoffee,
  mdiGlassCocktail,
  mdiBeer,
  mdiIceCream,
  mdiGlassMug,
  mdiChessRook,
  mdiCar,
  mdiLibrary,
  mdiAtm,
  mdiTheater,
  mdiFilmstrip,
  mdiCardsClub,
  mdiPalette,
  mdiWeb,
  mdiSlotMachine,
  mdiBookshelf,
  mdiShower,
  mdiRecycle,
  mdiToilet,
  mdiTrashCan,
  mdiTicket,
  mdiHome,
  mdiWater,
  mdiFountain,
  mdiGrill,
  mdiShowerHead,
  mdiCurrencyUsd,
  mdiMortarPestlePlus,
  mdiHospital,
  mdiHospitalBuilding,
  mdiTooth,
  mdiPaw,
  mdiMailbox,
  mdiMail,
  mdiPhone,
  mdiParking,
  mdiFuel,
  mdiBicycle,
  mdiBusStop,
  mdiTaxi,
  mdiEvStation,
  mdiCarKey,
  mdiFerry,
  mdiMotorbike,
  mdiTools,
  mdiSailBoat,
  mdiPoliceBadge,
  mdiFireTruck,
  mdiOfficeBuilding,
  mdiGavel,
  mdiCarWash,
  mdiStore,
  mdiCarCog,
  mdiCarInfo,
  mdiHomePlus,
  mdiGamepad,
  mdiSeesaw,
  mdiDumbbell,
  mdiGolf,
  mdiPool,
  mdiBaseballBat,
  mdiBeach,
  mdiFish,
  mdiBowling,
  mdiDogSide,
  mdiTablePicnic,
  mdiCampfire,
  mdiBinoculars,
  mdiTent,
  mdiCaravan,
  mdiInformation,
  mdiBed,
  mdiCamera,
  mdiShopping,
  mdiHairDryer,
  mdiBaguette,
  mdiNewspaper,
  mdiLipstick,
  mdiCow,
  mdiCharity,
  mdiBookOpen,
  mdiTshirtCrew,
  mdiSpeaker,
  mdiMusic,
  mdiMedicalBag,
  mdiGlassWine,
  mdiSmoking,
  mdiBagSuitcase,
  mdiVhs,
  mdiTea,
  mdiViolin,
  mdiWashingMachine,
  mdiTractor,
  mdiFlower,
  mdiSofa,
  mdiCellphone,
  mdiCup,
  mdiRug,
  mdiSync,
  mdiPaletteSwatch,
  mdiToyBrick,
  mdiPrinter,
  mdiLaptop,
  mdiShoeSneaker,
  mdiGlasses,
  mdiRing,
  mdiGift,
  mdiFoodCroissant,
  mdiTrainCar,
  mdiBasketball,
  mdiBeaker,
  mdiBottleTonic,
  mdiCupcake,
  mdiSausage,
  mdiCookie,
  mdiWindTurbine,
  mdiGate,
  mdiCastle,
  mdiGraveStone,
  mdiSpaceInvaders,
  mdiSack,
  mdiLighthouse,
  mdiSilo,
  mdiTransmissionTower,
  mdiTowerFire,
  mdiFireplace,
  mdiCrane,
  mdiTelescope,
  mdiAirplane,
  mdiTrain,
  mdiHelicopter,
  mdiCart,
  mdiHandsPray,
  mdiCarWrench
} from '@mdi/js'

// mdiBench should be in @mdi/js but isn't
const mdiBench = "M16 16L16 12L18.5 12L18.5 16L16 16ZM8 12L8 16L5.5 16L5.5 12L3 12L3 8L21 8L21 12L8 12Z"

const categoryTypeIconMap = {
  'aeroway': {
    'aerodrome': mdiAirplane,
    'helipad': mdiHelicopter
  },
  'railway': {
    'station': mdiTrain,
  },
  'highway': {
    'bus_stop': mdiBusStop,
  },
  'leisure': {
    'park': mdiPineTree,
    'outdoor_seating': mdiTablePicnic,
    'amusement_arcade': mdiSpaceInvaders,
    'playground': mdiSeesaw,
    'fitness_centre': mdiDumbbell,
    'fitness_stations': mdiDumbbell,
    'golf_course': mdiGolf,
    'water_park': mdiPool,
    'swimming_area': mdiPool,
    'sports_centre': mdiBaseballBat,
    'miniature_golf': mdiGolf,
    'beach_resort': mdiBeach,
    'fishing': mdiFish,
    'bowling_alley': mdiBowling,
    'dog_park': mdiDogSide,
    'picnic_table': mdiTablePicnic,
    'firepit': mdiCampfire,
    'bird_hide': mdiBinoculars,
    'slipway': mdiFerry
  },
  'boundary': {
    'national_park': mdiPineTree,
  },
  'power': {
    'generator': mdiWindTurbine
  },
  'man_made': {
    'storage_tank': mdiSilo,
    'silo': mdiSilo,
    'water_tower': mdiTowerFire,
    'chimney': mdiFireplace,
    'lighthouse': mdiLighthouse,
    'crane': mdiCrane,
    'windmill': mdiWindTurbine,
    'communications_tower': mdiTransmissionTower,
    'telescope': mdiTelescope,
  },
  'historic': {
    'monument': mdiChessRook,
    'memorial': mdiChessRook,
    'archaeological_site': mdiSack,
    'wayside_shrine': mdiGraveStone,
    'castle': mdiCastle,
    'fort': mdiChessRook,
    'city_gate': mdiGate,
  },
  'tourism': {
    'museum': mdiBank,
    'artwork': mdiPalette,
    'gallery': mdiPalette,
    'picnic_site': mdiTablePicnic,
    'camp_site': mdiTent,
    'caravan_site': mdiCaravan,
    'information': mdiInformation,
    'viewpoint': mdiCamera,
    'hotel': mdiBed,
    'guest_house': mdiBed,
    'hostel': mdiBed,
    'chalet': mdiBed,
    'motel': mdiBed,
    'apartment': mdiBed,
    'alpine_hut': mdiBed,
    'wilderness_hut': mdiBed,
  },
  'amenity': {
    'restaurant': mdiSilverwareForkKnife,
    'food_court': mdiSilverwareForkKnife,
    'cafe': mdiCoffee,
    'fast_food': mdiHamburger,
    'bar': mdiGlassCocktail,
    'pub': mdiGlassMug,
    'ice_cream': mdiIceCream,
    'biergarten': mdiBeer,
    'library': mdiLibrary,
    'theatre': mdiTheater,
    'cinema': mdiFilmstrip,
    'museum': mdiBank,
    'nightclub': mdiCardsClub,
    'arts_centre': mdiPalette,
    'internet_cafe': mdiWeb,
    'casino': mdiSlotMachine,
    'public_bookcase': mdiBookshelf,
    'public_bath': mdiShower,
    'toilets': mdiToilet,
    'recycling': mdiRecycle,
    'waste_basket': mdiTrashCan,
    'waste_disposal': mdiTrashCan,
    'vending_machine': mdiTicket,
    'bench': mdiBench,
    'shelter': mdiHome,
    'drinking_water': mdiWater,
    'fountain': mdiFountain,
    'bbq': mdiGrill,
    'shower': mdiShowerHead,
    'bank': mdiBank,
    'atm': mdiAtm,
    'bureau_de_change': mdiCurrencyUsd,
    'pharmacy': mdiMortarPestlePlus,
    'hospital': mdiHospitalBuilding,
    'clinic': mdiHospital,
    'dentist': mdiTooth,
    'veterinary': mdiPaw,
    'post_box': mdiMailbox,
    'post_office': mdiMail,
    'telephone': mdiPhone,
    'parking': mdiParking,
    'fuel': mdiFuel,
    'bicycle_parking': mdiBicycle,
    'bus_station': mdiBusStop,
    'bicycle_rental': mdiBicycle,
    'taxi': mdiTaxi,
    'charging_station': mdiEvStation,
    'car_rental': mdiCarKey,
    'parking_entrance': mdiParking,
    'ferry_terminal': mdiFerry,
    'motorcycle_parking': mdiMotorbike,
    'bicycle_repair_stations': mdiTools,
    'boat_rental': mdiSailBoat,
    'police': mdiPoliceBadge,
    'townhall': mdiOfficeBuilding,
    'fire_station': mdiFireTruck,
    'social_facility': mdiOfficeBuilding,
    'courthouse': mdiGavel,
    'prison': mdiBank,
    'place_of_worship': mdiHandsPray,
    'marketplace': mdiStore,
    'car_wash': mdiCarWash,
    'vehicle_inspection': mdiCarCog,
    'driving_school': mdiCarInfo,
    'nursing_home': mdiHomePlus,
  },
  'shop': {
    'car': mdiCar,
    'convenience': mdiStore,
    'supermarket': mdiCart,
    'clothes': mdiShopping,
    'fashion': mdiShopping,
    'hairdresser': mdiHairDryer,
    'bakery': mdiBaguette,
    'bicycle': mdiBicycle,
    'car_repair': mdiCarWrench,
    'doityourself': mdiTools,
    'hardware': mdiTools,
    'kiosk': mdiNewspaper,
    'newsagent': mdiNewspaper,
    'beauty': mdiLipstick,
    'butcher': mdiCow,
    'alcohol': mdiGlassCocktail,
    'wine': mdiGlassWine,
    'furniture': mdiSofa,
    'florist': mdiFlower,
    'mobile_phone': mdiCellphone,
    'electronics': mdiLaptop,
    'shoes': mdiShoeSneaker,
    'car_parts': mdiCarCog,
    'greengrocer': mdiStore,
    'farm': mdiTractor,
    'laundry': mdiWashingMachine,
    'dry_cleaning': mdiWashingMachine,
    'optician': mdiGlasses,
    'jewelry': mdiRing,
    'jewellery': mdiRing,
    'books': mdiBookshelf,
    'gift': mdiGift,
    'department_store': mdiStore,
    'confectionery': mdiCupcake,
    'chocolate': mdiCookie,
    'pastry': mdiFoodCroissant,
    'variety_store': mdiStore,
    'travel_agency': mdiTrainCar,
    'sports': mdiBasketball,
    'chemist': mdiBeaker,
    'computer': mdiLaptop,
    'stationary': mdiMail,
    'pet': mdiDogSide,
    'beverages': mdiCup,
    'cosmetics': mdiLipstick,
    'perfumery': mdiBottleTonic,
    'tyres': mdiCarWrench,
    'motorcycle': mdiMotorbike,
    'garden_centre': mdiFlower,
    'copyshop': mdiPrinter,
    'toys': mdiToyBrick,
    'deli': mdiSausage,
    'tobacco': mdiSmoking,
    'seafood': mdiFish,
    'interior_decoration': mdiPaletteSwatch,
    'ticket': mdiTicket,
    'photo': mdiCamera,
    'trade': mdiSync,
    'houseware': mdiGlassWine,
    'art': mdiPalette,
    'paint': mdiPalette,
    'fabric': mdiTshirtCrew,
    'bookmaker': mdiBookOpen,
    'second_hand': mdiCharity,
    'charity': mdiCharity,
    'bed': mdiBed,
    'medical_supply': mdiMedicalBag,
    'hifi': mdiSpeaker,
    'music': mdiMusic,
    'coffee': mdiCoffee,
    'musical_instrument': mdiViolin,
    'tea': mdiTea,
    'video': mdiVhs,
    'bag': mdiBagSuitcase,
    'carpet': mdiRug,
    'video_games': mdiGamepad,
    'dairy': mdiCup,
  }
}

function getMaterialDesignIcon (type, category) {
  let icon = null
  if (type != null && category != null && categoryTypeIconMap[category.toLowerCase()] && categoryTypeIconMap[category.toLowerCase()][type.toLowerCase()]) {
    icon = categoryTypeIconMap[category.toLowerCase()][type.toLowerCase()]
  }
  return icon
}

export {
  getMaterialDesignIcon
}
