const categoryTypeIconMap = {
  'aeroway': {
    'aerodrome': 'mdi-airplane',
    'helipad': 'mdi-helicopter'
  },
  'railway': {
    'station': 'mdi-train',
  },
  'highway': {
    'bus_stop': 'mdi-bus-stop',
  },
  'leisure': {
    'park': 'mdi-pine-tree',
    'outdoor_seating': 'mdi-table-picnic',
    'amusement_arcade': 'mdi-space-invaders',
    'playground': 'mdi-seesaw',
    'fitness_centre': 'mdi-dumbbell',
    'fitness_stations': 'mdi-dumbbell',
    'golf_course': 'mdi-golf',
    'water_park': 'mdi-pool',
    'swimming_area': 'mdi-pool',
    'sports_centre': 'mdi-baseball-bat',
    'miniature_golf': 'mdi-golf',
    'beach_resort': 'mdi-beach',
    'fishing': 'mdi-fish',
    'bowling_alley': 'mdi-bowling',
    'dog_park': 'mdi-dog-side',
    'picnic_table': 'mdi-table-picnic',
    'firepit': 'mdi-campfire',
    'bird_hide': 'mdi-binoculars',
    'slipway': 'mdi-ferry'
  },
  'boundary': {
    'national_park': 'mdi-pine-tree',
  },
  'power': {
    'generator': 'mdi-wind-turbine'
  },
  'man_made': {
    'storage_tank': 'mdi-silo',
    'silo': 'mdi-silo',
    'water_tower': 'mdi-tower-fire',
    'chimney': 'mdi-fireplace',
    'lighthouse': 'mdi-lighthouse',
    'crane': 'mdi-crane',
    'windmill': 'mdi-wind-turbine',
    'communications_tower': 'mdi-transmission-tower',
    'telescope': 'mdi-telescope',
  },
  'historic': {
    'monument': 'mdi-chess-rook',
    'memorial': 'mdi-chess-rook',
    'archaeological_site': 'mdi-sack',
    'wayside_shrine': 'mdi-grave-stone',
    'castle': 'mdi-castle',
    'fort': 'mdi-chess-rook',
    'city_gate': 'mdi-gate',
  },
  'tourism': {
    'museum': 'mdi-bank',
    'artwork': 'mdi-palette',
    'gallery': 'mdi-palette',
    'picnic_site': 'mdi-table-picnic',
    'camp_site': 'mdi-tent',
    'caravan_site': 'mdi-caravan',
    'information': 'mdi-information',
    'viewpoint': 'mdi-camera',
    'hotel': 'mdi-bed',
    'guest_house': 'mdi-bed',
    'hostel': 'mdi-bed',
    'chalet': 'mdi-bed',
    'motel': 'mdi-bed',
    'apartment': 'mdi-bed',
    'alpine_hut': 'mdi-bed',
    'wilderness_hut': 'mdi-bed',
  },
  'amenity': {
    'restaurant': 'mdi-silverware-fork-knife',
    'food_court': 'mdi-silverware-fork-knife',
    'cafe': 'mdi-coffee',
    'fast_food': 'mdi-hamburger',
    'bar': 'mdi-glass-cocktail',
    'pub':'mdi-glass-mug',
    'ice_cream':'mdi-ice-cream',
    'biergarten':'mdi-beer',
    'library':'mdi-library',
    'theatre':'mdi-theater',
    'cinema':'mdi-filmstrip',
    'museum':'mdi-bank',
    'nightclub':'mdi-cards-club',
    'arts_centre':'mdi-palette',
    'internet_cafe':'mdi-web',
    'casino':'mdi-slot-machine',
    'public_bookcase':'mdi-bookshelf',
    'public_bath':'mdi-shower',
    'toilets':'mdi-toilet',
    'recycling':'mdi-recycle',
    'waste_basket':'mdi-trash-can',
    'waste_disposal':'mdi-trash-can',
    'vending_machine':'mdi-ticket',
    'bench':'mdi-bench',
    'shelter':'mdi-home',
    'drinking_water':'mdi-water',
    'fountain':'mdi-fountain',
    'bbq':'mdi-grill',
    'shower':'mdi-shower-head',
    'bank':'mdi-bank',
    'atm':'mdi-atm',
    'bureau_de_change':'mdi-currency-usd',
    'pharmacy':'mdi-mortar-pestle-plus',
    'hospital':'mdi-hospital-building',
    'clinic':'mdi-hospital',
    'dentist':'mdi-tooth',
    'veterinary':'mdi-paw',
    'post_box':'mdi-mailbox',
    'post_office':'mdi-mail',
    'telephone':'mdi-phone',
    'parking':'mdi-parking',
    'fuel':'mdi-fuel',
    'bicycle_parking':'mdi-bicycle',
    'bus_station':'mdi-bus-stop',
    'bicycle_rental':'mdi-bicycle',
    'taxi':'mdi-taxi',
    'charging_station':'mdi-ev-station',
    'car_rental':'mdi-car-key',
    'parking_entrance':'mdi-parking',
    'ferry_terminal':'mdi-ferry',
    'motorcycle_parking':'mdi-motorbike',
    'bicycle_repair_stations':'mdi-tools',
    'boat_rental':'mdi-sail-boat',
    'police':'mdi-police-badge',
    'townhall':'mdi-office-building',
    'fire_station':'mdi-fire-truck',
    'social_facility':'mdi-office-building',
    'courthouse':'mdi-gavel',
    'prison':'mdi-bank',
    'place_of_worship':'mdi-hands-pray',
    'marketplace':'mdi-store',
    'car_wash':'mdi-car-wash',
    'vehicle_inspection':'mdi-car-cog',
    'driving_school':'mdi-car-info',
    'nursing_home':'mdi-home-plus',
  },
  'shop': {
    'car':'mdi-car',
    'convenience':'mdi-store',
    'supermarket':'mdi-cart',
    'clothes':'mdi-shopping',
    'fashion':'mdi-shopping',
    'hairdresser':'mdi-hair-dryer',
    'bakery':'mdi-baguette',
    'bicycle':'mdi-bicycle',
    'car_repair':'mdi-car-wrench',
    'doityourself':'mdi-tools',
    'hardware':'mdi-tools',
    'kiosk':'mdi-newspaper',
    'newsagent':'mdi-newspaper',
    'beauty':'mdi-lipstick',
    'butcher':'mdi-cow',
    'alcohol':'mdi-glass-cocktail',
    'wine':'mdi-glass-wine',
    'furniture':'mdi-sofa',
    'florist':'mdi-flower',
    'mobile_phone':'mdi-cellphone',
    'electronics':'mdi-laptop',
    'shoes':'mdi-shoe-sneaker',
    'car_parts':'mdi-car-cog',
    'greengrocer':'mdi-store',
    'farm':'mdi-tractor',
    'laundry':'mdi-washing-machine',
    'dry_cleaning':'mdi-washing-machine',
    'optician':'mdi-glasses',
    'jewelry':'mdi-ring',
    'jewellery':'mdi-ring',
    'books':'mdi-bookshelf',
    'gift':'mdi-gift',
    'department_store':'mdi-store',
    'confectionery':'mdi-cupcake',
    'chocolate':'mdi-cookie',
    'pastry':'mdi-food-croissant',
    'variety_store':'mdi-store',
    'travel_agency':'mdi-train-car',
    'sports':'mdi-basketball',
    'chemist':'mdi-beaker',
    'computer':'mdi-laptop',
    'stationary':'mdi-mail',
    'pet':'mdi-dog-side',
    'beverages':'mdi-cup',
    'cosmetics':'mdi-lipstick',
    'perfumery':'mdi-bottle-tonic',
    'tyres':'mdi-car-wrench',
    'motorcycle':'mdi-motorbike',
    'garden_centre':'mdi-flower',
    'copyshop':'mdi-printer',
    'toys':'mdi-toy-brick',
    'deli':'mdi-sausage',
    'tobacco':'mdi-smoking',
    'seafood':'mdi-fish',
    'interior_decoration':'mdi-palette-swatch',
    'ticket':'mdi-ticket',
    'photo':'mdi-camera',
    'trade': 'mdi-sync',
    'houseware': 'mdi-glass-wine',
    'art': 'mdi-palette',
    'paint': 'mdi-palette',
    'fabric': 'mdi-tshirt-crew',
    'bookmaker': 'mdi-book-open',
    'second_hand': 'mdi-charity',
    'charity': 'mdi-charity',
    'bed': 'mdi-bed',
    'medical_supply': 'mdi-medical-bag',
    'hifi': 'mdi-speaker',
    'music': 'mdi-music',
    'coffee': 'mdi-coffee',
    'musical_instrument': 'mdi-violin',
    'tea': 'mdi-tea',
    'video': 'mdi-vhs',
    'bag': 'mdi-bag-suitcase',
    'carpet': 'mdi-rug',
    'video_games': 'mdi-gamepad',
    'dairy': 'mdi-cup',
  }
}

function getMaterialDesignIcon (type, category) {
  let icon = null
  if (type != null && category != null && categoryTypeIconMap[category.toLowerCase()] && categoryTypeIconMap[category.toLowerCase()][type.toLowerCase()]) {
    icon = categoryTypeIconMap[category.toLowerCase()][type.toLowerCase()]
  }
  return icon
}

export {
  getMaterialDesignIcon
}
